---
apiVersion: v1
kind: Namespace
metadata:
  name: kvm-device-plugin
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: kvm-device-plugin
  namespace: kvm-device-plugin
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    name: kvm-device-plugin
  name: kvm-device-plugin
  namespace: kvm-device-plugin
spec:
  selector:
    matchLabels:
      name: kvm-device-plugin
  template:
    metadata:
      labels:
        name: kvm-device-plugin
    spec:
      serviceAccountName: kvm-device-plugin
      containers:
      - name: kvm-device-plugin
        image: docker.io/kaasops/kvm-device-plugin:v1.0.0
        securityContext:
          privileged: true
        volumeMounts:
          - name: device-plugin
            mountPath: /var/lib/kubelet/device-plugins
      volumes:
        - name: device-plugin
          hostPath:
            path: /var/lib/kubelet/device-plugins